---
title: "Growth in Diagnostic Testing<br>and Its Impact on<br>Emergency Departments"
subtitle: "November 2024"
author: 
  - name: Steven Wyatt
    email: swyatt@nhs.net
    corresponding: TRUE
    affiliation: The Strategy Unit
  - name: Andrew Jones
    email: swyatt@nhs.net
    corresponding: FALSE
# date: 2024-11-29
format:
  html:
    html-table-processing: none
    # code-fold: true
    code-tools: true
    embed-resources: true
    grid:
      margin-width: 200px
  pdf: default
reference-location: margin
citation-location: margin
toc: true
toc-title: Contents
toc-location: left
theme: journal
fig-cap-location: top
number-sections: false
title-block-banner: '#f8be06'
title-block-banner-color: '#242322'
# mainfont: Gill Sans MT
# mainfont: Helvetica
editor_options: 
  chunk_output_type: console
---

# Executive Summary

Andrew Jackson's desired template:

Last time we said this, now we're saying this. Where is the new work consistent with past work - where different.

\[He is intending to use this as further evidence to suggests that 4HR target is not appropriate\]

# Introduction

Over the last decade, the growth in diagnostic testing in EDs has been rapid. Earlier analysis conducted by the Strategy Unit (2019, 2023) suggests that this growth may have implications for the timeliness of patient care, for decisions on whether to admit a patient, and for crowding in EDs.

In this work, we revisit.... / update selected analyses from these past reports.

In Phase I of the project, we seek answers to five questions:

1.  How has the average number of tests per ED attendance changed over time?

2.  For each of the 20+ test types, how much more likely is it that a patient will receive a test in ED in year 2023/24 than in year 2019/20?

3.  What proportion of the growth in each test, can be attributed to: (a) increases in raw demand; (b) changes in case-mix; and (c) changes in the propensity to test (i.e. clinical practice)?

4.  How much (net) time does a test add to a patient’s stay in ED?

5.  How do tests influence decisions to admit?

## Why do we seek (updated) answers to these questions???

A second phase of this project, planned for completion in, will look at ...

*For the sake of readability, we use the term, “test” to refer to a unit of diagnostic activity. We acknowledge that some of these “tests” might also be therapeutic procedures.*

# General Analytical Approach

Emergency Departments

To address the questions above \[link?\], we relied on SUS A&E and EC data sets.

Our analyses covered persons with a postcode in England who had an unplanned attendances at major emergency (Type 1) departments.

We included only complete attendances, so we excluded dead on arrival or died during attendance.

patients who left before being treated or who were streamed to other care services.

### Our use of sampling

Whilst SUS A&E and EC data sets are relatively high-quality sources, we observed considerable variation in recording practices, both across the population of provider trusts and over time. If overlooked, this variation would adversely affect both the *reliability* and *validity* of our results. \[links to meanings\]

Therefore, to ensure that data quality met our requirements for a given question, we carried out these analyses on samples of providers These were non-random samples: we included a provider in a sample if the quality of their data submissions meet our requirements for the given question.

Whilst there were several different types of question we aimed to answer, we identified two samples. one sample of providers for Question 1 and another sample for Questions 2 to 5.

This sampling approach to improve the reliability and validity of our results. However, since we also wish make general statements about the effect of diagnostic testing on urgent and emergency care, we must ensure that our sample and our population (in each case) have similar properties. Our sample of providers must be *representative* of the population of providers.

There is a trade-off to be made here. The larger the sample of providers we select, the more likely it will be that this

The more providers we capture in our sample, the more likely the sample is to be representative of the population of providers. With a representative sample, we can be more confident that our findings for the sample are also applicable to the population.

A large sample of providers is more likely to be representative of the population of providers. But the larger we make our sample, the more we must compromise on data quality the lower we data quality threshold becomes, which is in turn likely to decrease the the reliability of our results.

Details of the sampling approaches, and measures of representation, and our on the trade-off above, can be found in Appendix 1.

Details of the specific approaches to each question can be found in the "Methods and Limitations" boxes in the applicable parts of the Analysis section.

# Analysis

## Perhaps some context?

describe the pop attending EDs show the casemix in both years, age, condtion... can't exclude all casemix effects

## Q1. How have rates of testing in EDs changed over time?

We start by looking at How has the average number of tests per ED attendance changed over time?

This analysis covers a period of 12 years. Other summary details.

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
# Q1: Methods and Limitations

###### Methods

As noted above, this analysis covers a period of 12 years and therefore spans A&E and EC data sets (each of which has a slightly different structure).

We identified XXX providers with provider codes that survived across the 12 year study period and that, in addition, passed basic data quality checks. These XXX providers represent the total population of providers that we might have used for our analysis had data quality been universally high.

Providers were included in our sample if their data submissions met the quality required for this question. Here, the study period is relatively long but we have few variables to examine. We are looking to see that:

1.  Throughout the study period, providers have had consistently high levels of recording of the investigation fields.

2.  For attendances in which multiple investigations of the same type have been carried out, providers have recorded each instance of the investigation (and have been consistent in this practice over the whole study period).

We established that XX providers met these criteria. The providers we intend to use for our sample are given in @tbl-sample-q1. In the adjacent tab, @tbl-representation suggests that this sample of XXX providers is widely representative of the population of providers. We note that the sample includes higher proportions of larger providers and providers in London, and lower proportions of smaller providers and providers in the East of England.

###### Limitations

And these are the limitations we have identified.
:::

@fig-trend shows results for Question 1, based on data from the sample of XXX providers identified above. It appears that, overall, test rates have doubled over the study period, from an average of 2 tests per attendance in 2012/13 to 4 tests per attendance in 2023/24. The rate of increase for admitted patients was uneven and appears to have slowed over the period (now normalising after the pandemic-related spike 2020/2021). For the 7 in 10 patients who are are not admitted after an ED attendance, the increase was fairly consistent to 2020. Again, the rate of increase seems to have slowed following the spike in test rates (seen across the majority of test types) in 2020/21. Note also fewer attendances during covid and likely more serious, so test rates increased.

## Q2. Are patients more likely to receive tests today than they were in 2019/20? 

How much more likely was a patient to receive a test in an ED in 2023/24 compared to 2019/20?

Start off with some intro text from Diagnostics report 2023

Are patients more likely to receive tests today than they were in 2019/20?

## Q3. What is driving test growth in EDs?

Q3. Is the growth in EDs being driven by changes to demand, case-mix, or practice?

## Q4. How much time do tests add to a patient's stay in the ED?

How much (net) time does a test add to a patient’s stay in ED?

## Q5. How do tests influence decisions to admit?

More text here.

# Discussion

# Appendix 1

Sampling and SQL queries ? Collapsable?

<!-- To carry out these analyses, we require only the EC data set, and only two years (provisionally, 2019/20 and 2023/24). We intend to use different samples to answer the different types of question). We will include a provider in a sample if the quality of their data submissions meet our requirements for the given question. We expect this approach to  -->

### Sampling for Q1 (from trends dq)

Given that we will be covering a relatively long period, spanning two
data sets (with slightly different structures), it will be important to
understand the quality and consistency of recording practices, both over
time and by provider. In earlier [work in this area](https://www.strategyunitwm.nhs.uk/publications/waiting-times-and-attendance-durations-english-ae-departments),
we based our analysis on subsets of providers who had a history of high
quality data. For this analysis, it is likely that we will, again, have
to work with data from a subset providers.

There is more - will have to look.

## Sampling for Q2 (from ECDS DATA qual qmd)

One solution to this problem may be to use other variables to understand case-mix (and may even be more valid measures). For example, the combination of *acuity* (composed of 5 levels) and Chief Complaint Group (15 groups) should allow us to account for differences in case-mix. Both variables have \<13% NULL values in both years when looking at the data set as a whole. The completion rates would likely improve further if we were to examine a subset of providers.

It is possible, then, that the quality of a provider’s submission of these two variables, along with *Der_EC_Investigation_All*, may determine whether we include the provider in our analyses. We will address this idea next.

we deduce that 16 providers can claim to have **all 3 fields** **complete** for \>90% of attendances, in both years. If we were to relax the threshold to \>85%, we get just four more providers.

### How representative is the provider sample?

We identified 102 providers with provider codes that were present in the two years of interest and that, in addition, passed basic data quality checks. These providers will represent the total population of providers that we might have used for our analyses. Given the data quality issues, we have selected a sample of providers to improve the reliability and validity of our results. However, since we wish to make general statements about about the effect of diagnostic testing on urgent and emergency care, we must ensure that our samples are representative of the population of providers.

More deprived, and older population, with more arrivals by ambulance results in more admissions. We will control for all of these factors - what difference does this make…?
